export const SUGGESTIONS = 'SUGGESTIONS';
export const GET_WEATHER = 'GET_WEATHER';
export const CURRENT_CONDITIONS = 'CURRENT_CONDITIONS';
export const FAVORITES_CONDITIONS = 'FAVORITES_CONDITIONS';
